### ISSUE TITLE
Error in dimnames(coeftab) <- list(coef.table$term, c("Estimate", "Bias",  :    'dimnames'的长度[2]必需与陈列范围相等

### ISSUE THREAD

**Issue by zhangyz1997** [adayim/causalMed#1]
您好, 我今天尝试在R 3.6.3上运行README.md提供的示范, 但是在输出summary(out)的时候遇到了如下报错, 请问该如何解决呢? 谢谢
`Error in dimnames(coeftab) <- list(coef.table$term, c("Estimate", "Bias",  : 
  'dimnames'的长度[2]必需与陈列范围相等
`
![批注 2020-04-10 204618](https://user-images.githubusercontent.com/22343073/78991843-781be580-7b6c-11ea-8388-c2bf9fd2f320.png)

**Comment by adayim** [comment]
您好，非常感谢将问题反馈给我，已经对里面存在的问题做了修改，现在应该是可以了。这个是里面命名的时候出现的问题，请重新尝试以下。
